---
title: "FinalDashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: https://github.com/TessSam/EDLD652final_project
    theme: yeti
---

```{r setup, include=FALSE}
library(flexdashboard)
library(gganimate)#might not use
library(forcats)
library(ungeviz)
library(broom.mixed)
library(here)
library(rio)
#library(foreign)#importing data from spss
library(tidyverse)
library(gridExtra)#
library(lme4) #glm mixed effects
library(RColorBrewer) 
library(corrplot) #graphical display of a correlation matrix, confidence interval
library(gee) #Generalized estimation equation,
library(ez) #factorial analysis stuff
library(effects) #displaying of linear model effects

#cb friendly palette using black
#cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

```{r P1_data_organization, include=FALSE}
# Stage1 - Data Loading and Organization
#=============================================================
#set seed
set.seed(652)
# READING FILES
#Beh_text <- read.delim('LetDriftGo_expcCue_BehP.txt', header=TRUE, fill=TRUE)
Beh_text <- import(here::here("LetDriftGo_expcCue_BehP.txt"))

ds<-Beh_text;
head(ds)

#scramble ds RT just incase I cant use raw lab data
# set.seed(009)
# RT <- sample(nrow(ds))
# scramble <- ds[RT,]

#Add trial grouping variable 
ds$BTRIAL = (max(ds$TRIAL)*ds$BLOCK-1)+ds$TRIAL

#Add category for correct answer(1)
ds$Category <- ds$CATEGORY;
ds$Category[ds$Category==2] <- 0;
ds$Category<-as.integer(ds$Category)

# # Cue-driven expectancy context, valid if expectation cue is consistant with correct trial axis group it is valid, if not it is invalid  
#recode cuetype values to fit b value for adaptive gain model
ds$CUETYPE<-dplyr::recode(ds$CUETYPE, `1` = "valid", `0` = "invalid")#
ds$CUECATb<-ds$CUECAT;
#t1 and -1 distinction necessary for calculating cue evidence compatability Ck value in model
ds$CUECATb[ds$CUECATb==2] <- -1

# Checks for correct variable creation 
head(ds$CUECAT)
head(ds$CUECATb)

# Checking
#any(ds$CUECAT[ds$DVCP2CUE_1==1]==ds$DVCAT_1[ds$DVCP2CUE_1==1])

# #Evidence-driven expectancy
# Factorize for model input
cols<-colnames(ds)
cols<-cols[grepl("DVCP2CUE",cols)]
ds[cols] <- lapply(ds[cols], factor)

# Exclude subjects(cant remember why, probably not paying attention)
ds<-subset(ds,SUBID!=228 & SUBID!=231)


# PGROUP (1 = high performer 0 = low performer, median, may have had to do this as subject numbers were low)
# median split data for high and low perfamnace subject distinction 
ds<-ds%>%
  group_by(SUBID)%>%
    summarize(ACC=mean(ACC))%>%
      mutate(PGROUP=as.numeric(ACC>median(ACC)))%>%
        dplyr::select(c(SUBID,PGROUP))%>%
          left_join(ds,by=("SUBID"))

##Datavis plot 1
## Stage2-Behavior Analysis ( mean aggregate of accuracy by cuetype)

#Aggregated mean for accuracy by cuetype 
# ACC:Cue efffect
acc_exp<-ds %>% 
  group_by(SUBID,CUETYPE) %>% 
    summarise(ACC=mean(ACC))
      
#df for plotting mean and error bars 
sumacc <- acc_exp %>% 
  group_by(CUETYPE) %>%
    summarise_each(funs(mean,se=sd(.)/sqrt(n())),ACC) %>% 
  #dont know if this fixed it but it workds
      rename(ACC = mean) %>%
        group_by(CUETYPE)
        #as.data.frame()

```

```{css echo = FALSE}
@import url('https://fonts.googleapis.com/css2?family=Crimson+Text&display=swap');

body {
  font-family: 'Crimson Text', serif;
  background-color: #00aec2;
}

```
**Plot1**
===============================
Plot1 Notes {.sidebar}
-----------------------------------------------------------------------
These figures highlighted in plot 1 are visualizations of the mean accuracy of participants
sepparately for a expectation cue and stimulus stream consistancy conditions during a cue biased
multisampling judgement task. The cue indicated the correct category of the stream 70% of the
time and elements in the stream were categorically assigned to one of 2 axis groups.
Participants were instructed to correctly identify the overall cateory of the stream. The
**Invalid** category indicates the trials in which the expectation cue presented before the
stimulus stream was not consistant with its correct identity. The **Valid** category indicates
trials in which the expectation cue presented before the stream was consistat with
its overall identity.  

**1st Iteration:** Constructed using geom_bar() with error bars visualized through
geom_errorbar().

**2nd Iteration:** Constructed using geom_jitter() to replace geom_bar with participant mean
scores around consistancy conditions. Problems correctly segmenting a bar indicating the mean
value for each group with geom_hline().

**3rd Iteration:** Correctly implementing segmented group mean bars using annotate() to manually
place and lable them.
 


Column {data-width=550}
-----------------------------------------------------------------------

### **3rd Iteration**

```{r}
plot1.3 <- 
  ggplot(data = acc_exp, 
         aes(CUETYPE, ACC, color = CUETYPE)) +
  geom_errorbar(data = sumacc,
                aes(ymin = ACC - se,
                    ymax = ACC + se,
                    colour = "black"),
                    width = 0.2,
                    position = position_dodge(0.5)) +
  geom_jitter(width = 0.2, 
              height = 0,
              size = 2.5) +
   annotate("segment", x = 0.8, xend = 1.2, 
           y = sumacc$ACC[1], yend =sumacc$ACC[1],
           color = "#0072B2") +
   annotate("text", label = "Mean = 0.439", x = 0.8 - 0.1,
           y = sumacc$ACC[1]+0.02,
           color = "#0072B2") +
   annotate("segment", x = 1.8, xend = 2.2, 
           y = sumacc$ACC[2], yend =sumacc$ACC[2],
           color = "#009E73") +
    annotate("text", label = "Mean = 0.687", x = 1.7,
           y = sumacc$ACC[2]+0.02,
           color = "#009E73") +
  scale_color_manual(labels = c("Error Bar", "Mean Invalid \nAccuracy/Person", "Mean Valid \nAccuracy/Person"),
                     values=c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2")) +
  labs(title = "Mean Accuracy Across Participants \nfor Valid/Invalid Cues", 
       x = " Expectation Cuetype",
       y = "Accuracy",
       color = "Legend") +
  theme_bw() +
  theme(plot.title = element_text(size =16,face='bold'))+
                  theme(legend.text=element_text(family="Helvetica",
                                                 size=8),
                        legend.title = element_text(family="Helvetica",
                                                    size=11,
                                                    face="bold"),
                        legend.background = element_rect(fill="transparent")) +
                  theme(axis.text=element_text(size=13,
                                               face="bold"))+
                  theme(axis.title=element_text(family="Helvetica", 
                                                face="bold",
                                                vjust=0.8)) 

plot1.3
```

Column {data-width=400}
-----------------------------------------------------------------------

### **2nd Iteration**

```{r}
plot1.2 <- 
  ggplot(data = acc_exp, 
         aes(CUETYPE, ACC, color = CUETYPE)) +
  # geom_segment(data = sumacc,
  #              aes(y=ACC,
  #                  yend = ACC,
  #                  x= CUETYPE,
  #                  xend = CUETYPE,
  #                  width = 2)) +
  geom_hline(data = sumacc,
             aes(yintercept=ACC,
                 color = CUETYPE,
                 linetype = CUETYPE)) +
  geom_errorbar(data = sumacc,
                aes(ymin = ACC - se,
                    ymax = ACC + se,
                    colour = "CUETYPE"),
                    width = 0.2,
                    position = position_dodge(0.5)) +
  geom_jitter(width = 0.2, 
              height = 0,
              size = 2.5) +
  scale_color_manual(values=c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2")) +
  labs(title = "Mean Accuracy Across Participants for Valid/Invalid Cues", 
       x = " Expectation Cuetype",
       y = "Accuracy") +
  theme_bw()
plot1.2

```
Column {data-width=400}
-----------------------------------------------------------------------

### **1st Iteration**

```{r}
plot1.1 <- sumacc %>% 
  ggplot(aes(CUETYPE, ACC)) +
  geom_bar(stat = "identity", 
           fill = "black", 
           width = 0.6,
           position = position_dodge()) +
  geom_errorbar(aes(ymin = ACC - se, 
                    ymax = ACC + se), 
                width = 0.2,
                colour = "grey",
                position = position_dodge(0.5)) +
  labs(title = "Mean Accuracy Across Participants for Valid/Invalid Cues", 
       x = " Expectation Cuetype",
       y = "Accuracy") +
  theme_minimal()
plot1.1
```

```{r P2_data_organization, include=FALSE}
## Plot2
## group individual accuracy by expectation cue category


# RT:Cue effect, not using 
rt_exp<-ds %>% 
  group_by(SUBID,CUETYPE) %>% #group subject ID and expectation cuetype 
    summarise(RT=mean(RT))%>% 
      group_by(CUETYPE) %>% 
        summarise_each(funs(mean, se=sd(.)/sqrt(n())),RT)

# Check individual accuracy, for each subject average cuetype specific accuracy
acc_ind<-ds %>% 
  group_by(SUBID,CUETYPE) %>% 
    summarise(ACC=mean(ACC));print(acc_ind) 


# pivot_wider and ggplot(fantastic), tips from Raleigh
# create df with valid and invalid RT columns
acc_ind_wide <- acc_ind %>%
  pivot_wider(names_from = CUETYPE, values_from = ACC)  
    

cor(acc_ind$ACC[acc_ind$CUETYPE=="valid"],acc_ind$ACC[acc_ind$CUETYPE=="invalid"])

#bootstrapper object     
bsr <- bootstrapper(20, group = NULL)
```

**Plot2**
===============================
Plot2 Notes {.sidebar}
-----------------------------------------------------------------------
The figures highlighted in plot 2 are visualizations of the correlation between
**_individual_** mean accuracy values of **Invalid** cue trials and **Valid** cue trials. The
plot indicates individuals reling on the expectation cue tend to have higher accuracy during
valid trials and lower accuracy during invalid trials (and vice versa).

**1st Iteration:** Constructed using plot() and indexing valid/invalid rows of dataset. 

**2nd Iteration:** Constructed using ggplot(), geom_point(), and geom_smooth(). Initially
included very wrong effect size value.

**3rd Iteration:** Implemented an animated layer of the regression line using bootstrapper().
Colorblind friendly palatte also implemented alongside minor changes to figure fonts.   
 

Column {data-width=550}
-----------------------------------------------------------------------

### **3rd Iteration**

```{r}
# ggplot plotting correlation for grouped mean accuracy
#add some annotation for effect size, tips from Raleigh 
#clearer figure axes, tips from Anwesha
plot2.3 <-  acc_ind_wide %>%  
  ggplot(aes(valid, invalid)) +
  geom_smooth(method = "lm", 
              color = NA, 
              size = 1.5, 
              se = T) + 
    geom_point(size = 1,
               alpha = 0.6,
               color = "grey80") +
      geom_point(data = bsr, 
                 color = "#00ff95") +
        geom_smooth(data = bsr, 
                    method = "lm", 
                    color = "#00ff95", 
                    fullrange = T, 
                    se = F) +
          annotate('text', 
                   x = 0.86, 
                   y = 0.75,
                   label = "R^{2} == -0.774", parse = T, size = 5) +
            labs(title = "Correlation of Individual Mean Accuracy Values \nBetween Valid and Invalid Cue Trials", 
            subtitle = "",
              x = "Valid Cue Accuracy",
              y = "Invalid Cue Accuracy") +
                  theme_light()+
                  theme(plot.title = element_text(size =16,face='bold'))+
                  theme(legend.text=element_text(family="Helvetica",
                                                 size=9,
                                                 face="bold"),
                        legend.title = element_text(family="Helvetica",
                                                    size=11,
                                                    face="bold"),
                        legend.background = element_rect(fill="transparent")) +
                  theme(axis.text=element_text(size=13,
                                               face="bold"))+
                  theme(axis.title=element_text(family="Helvetica", 
                                                face="bold",
                                                vjust=0.8)) +
                  transition_states(.draw, transition_length = 0) +
                    ease_aes()

animate(plot2.3, fps=5)
```

Column {data-width=400}
-----------------------------------------------------------------------

### **2nd Iteration**

```{r}
# ggplot plotting correlation for grouped mean accuracy  
plot2.2 <- acc_ind_wide %>% 
  ggplot(aes(valid, invalid)) +
  geom_point(size = 4) +
  geom_smooth(method = "lm", color = "red", size = 1.5, se = F) + 
  annotate('text', 
           x = 0.86, 
           y = 0.75,
           label = "eta^{2} == 0.495", 
           parse = T, 
           size = 5)
  labs(title = "Correlation Between Accuracy on Valid and Invalid Cue Type", 
       subtitle = "Accuracy grouped by subject ID and Cuetype before averaging",
       x = " Accuracy Among Valid Cues",
       y = "Accuracy Among Invalid Cues") +
  theme_light()
plot2.2

```
Column {data-width=400}
-----------------------------------------------------------------------

### **1st Iteration**

```{r}
plot2.1 <- plot(acc_ind$ACC[acc_ind$CUETYPE=="valid"],acc_ind$ACC[acc_ind$CUETYPE=="invalid"])

```

```{r P3_data_organization, include=FALSE}
## Stage3-Modeling (Datavis plot3)
#================================================================
      
# Cue-expectancy 
# DVCP2CUE (0=incongruent 1 = congruent)
m2_expcmp=glmer(PCARD~1+CUECATb+(DV_1+DV_2+DV_3+DV_4)+(DV_1:DVCP2CUE_1+DV_2:DVCP2CUE_2+DV_3:DVCP2CUE_3+DV_4:DVCP2CUE_4)+(1|SUBID),family=binomial,data=subset(ds,PGROUP==0))
summary(m2_expcmp)
plot(allEffects(m2_expcmp)) 


#Process5-Plotting-
#======================================================================================================

#tidyway of formating mixed models for plot 
tidied_m <- broom.mixed::tidy(m2_expcmp, conf.int = TRUE)

#evidence position
EVnum<-rep(seq(1,4,1),2);
#congruency effect distinction
cond<-c(rep("incongruent",1,4),rep("congruent",1,4));
#effects for each position separately for congruency(consistant or inconsistant) with cue category, adjust negative values?
#with adding
coefs<- unlist(c(tidied_m[3:6,4],tidied_m[3:6,4]+tidied_m[7:10,4]));
# data frame for plotting, initial plotting wrong or missing something using tidy
ds_p2 <-
  data.frame(EVnum=EVnum,
             cond=cond,
             Estimate=c(coefs),
             stderr=tidied_m$std.error[3:10],
             conf.low = abs(tidied_m$conf.low[3:10]),
             conf.high =tidied_m$conf.high[3:10])

row.names(ds_p2) <- tidied_m$term[3:10]

ds_p2

#organization for plot3.3
#tidyway of formating mixed models for plot 
tidied_m <- m2_expcmp %>% 
  broom.mixed::tidy(conf.int = TRUE)  
#keeping only fixed effects
tidied_m <- tidied_m[-c(1,2,11),]
tidied_m$group[1:8] <- c(rep("incongruent",1,4),rep("congruent",1,4)) 
#accounting for partical effects?
tidied_m$estimate[5:8]<- unlist(c(tidied_m[1:4,4]+tidied_m[5:8,4]))
#evidence position
tidied_m <- tidied_m %>% mutate(evnum = as.numeric(rep(seq(1,4,1),2)))

```

**Plot3**
===============================
Plot3 Notes {.sidebar}
-----------------------------------------------------------------------
Mock figures plotting the coefficients of the fixed effects from a generalized linear mixed
model as decision weights in predicting a cardinal trial identity. **Congruent** indicates trial
elements within trial presentation position that were consistant with the expectaion cue.
**Incongruent** indicates elemetns specific to position that were not consistant with the
expectation cue. Potential missing predictors in model may skew interpreation but congrency
effect differences are stronger in position 1. As evidence accumulates, weights of each
congruency group for each evidence position becomes similar.     

**1st Iteration:** Constructed using ggplot(), geom_line, and geom_point. Used theme to manipulate plot text font and identity. 

**2nd Iteration:** Implemented correct mapping of error bars which did not work initially due to data formatting. Potentially(?) colorblind freindly color palette used for congruency category.

**3rd Iteration:** Failed implimentation of stat_confidence_density() for CI visualization. Defaulted to geom_ribbon to implement hypothetical error bars connecting positions, potentially usefuly for a visualizing experiment using more element positions to track decision weights.     


Column {data-width=550}
-----------------------------------------------------------------------

### **3rd Iteration**

```{r}
plot3.3 <- tidied_m %>% 
  ggplot(aes(x = evnum,
             y =estimate,
             color = group)) + 
    #cant get it to work
   # stat_confidence_density(aes(x = estimate, moe = std.error, group = evnum, confidence = 0.95),data = tidied_m) +
  #geom_errorbar(aes(ymin=conf.low, ymax=conf.high), width=.25,size=.5)+
    geom_errorbar(aes(ymin=estimate-std.error, 
                      ymax=estimate+std.error), 
                      width=.25,
                      size=.5)+
    geom_line(size=2)+
    geom_ribbon(aes(ymin = estimate - std.error,
                    ymax = estimate + std.error,
                    fill = group),
                    alpha = 0.1,
                    show.legend = F) +
    geom_point(size=6)+
    #Aesthetics!--------------------------------------------------------
                  theme_bw()+
                  scale_y_continuous(limits=c(0,1.5),
                                     breaks=seq(0,1.5,0.25))+
                  scale_x_continuous(breaks=1:8)+
                  scale_color_manual(values=c("#E69F00", "#56B4E9"))+
                  ylab("Decision Weight")+
                  xlab("Element Position")+
                  labs(color = "Cue-Element Congruency")+
                  ggtitle('Decision weights for each piece of evidence \ngrouped by congruency of cued category')+
                  theme(plot.title = element_text(size =15,face='bold'))+
                  theme(legend.position = c(0.82,0.8),
                        legend.key = element_blank(),
                        legend.text=element_text(family="Helvetica",
                                                 size=9,
                                                 face="bold"),
                        legend.title = element_text(family="Helvetica",
                                                    size=11,
                                                    face="bold"),
                        legend.key.size=unit(1,"cm"),
                        legend.background = element_rect(fill="transparent")) +
                  theme(axis.text=element_text(size=14,
                                               face="bold"))+
                  theme(axis.title=element_text(family="Helvetica", 
                                                face="bold",
                                                vjust=0.8))
                

plot3.3
```

Column {data-width=400}
-----------------------------------------------------------------------

### **2nd Iteration**

```{r}
plot3.2 <- ds_p2 %>% 
  ggplot(aes(x=EVnum, y=Estimate,group=cond,color=cond)) + 
  #geom_errorbar(aes(ymin=conf.low, ymax=conf.high), width=.25,size=.5)+
    geom_errorbar(aes(ymin=Estimate-stderr, 
                      ymax=Estimate+stderr), 
                      width=.25,
                      size=.5)+
    geom_line(size=2)+
    geom_point(size=6)+
    #Aesthetics!--------------------------------------------------------
                  theme_bw()+
                  scale_y_continuous(limits=c(0,1.5),
                                     breaks=seq(0,1.5,0.25))+
                  scale_x_continuous(breaks=1:8)+
                  scale_color_manual(values=c("#E69F00", "#56B4E9"))+
                  ylab("Decision Weight")+
                  xlab("Element Position")+
                  labs(color = "Cue-Element Congruency")+
                  ggtitle('Decision weights for each piece of evidence \ngrouped by congruency of cued category')+
                  theme(plot.title = element_text(size =15,face='bold'))+
                  theme(legend.position = c(0.8,0.8),
                        legend.key = element_blank(),
                        legend.text=element_text(family="Helvetica",
                                                 size=9,
                                                 face="bold"),
                        legend.title = element_text(family="Helvetica",
                                                    size=11,
                                                    face="bold"),
                        legend.key.size=unit(1,"cm"),
                        legend.background = element_rect(fill="transparent")) +
                  theme(axis.text=element_text(size=14,
                                               face="bold"))+
                  theme(axis.title=element_text(family="Helvetica", 
                                                face="bold",
                                                vjust=0.8))
                

plot3.2

```
Column {data-width=400}
-----------------------------------------------------------------------

### **1st Iteration**

```{r}
plot3.1<- ggplot(ds_p2, aes(x=EVnum, y=Estimate,group=cond,color=cond)) + 
        geom_line(size=2)+geom_point(size=6)+
        #Aesthetics!-------------------------
        scale_y_continuous(limits=c(0,1.5),breaks=seq(0,1.5,0.25))+
        scale_x_continuous(breaks=1:8)+
        scale_color_manual(values=c("black","red"))+
        ylab("Decision Weight")+xlab("Element Position")+#ggtitle('')+
        theme(plot.title = element_text(size =20,face='bold'))+
        theme(legend.key = element_blank())+
        #theme(legend.position="none")+
        theme(legend.position=c(0.45,0.9),legend.text=element_text(size=15,face="bold"),legend.direction="horizontal",legend.title = element_blank(),legend.key.size=unit(1,"cm")) +
        theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
        theme(axis.text=element_text(size=14,face="bold"))+
        theme(axis.title=element_text(family="Helvetica", face="bold",vjust=0.8))+ 
        theme(strip.text=element_text(family="Helvetica", face="bold",vjust=0.4,size=10))+
        theme(strip.text=element_text(family="Helvetica", face="bold",vjust=0.4,size=12))+
        theme(strip.background=element_blank())
plot3.1

```
